### ISSUE TITLE
Volume Rendering Example

### ISSUE THREAD

**Issue by ulricheck** [moderngl/moderngl#118]
Here is a link to the promised volume raycasting example:

[Volume Raycasting Example](https://github.com/ulricheck/ModernGL-Volume-Raycasting-Example)

there are a couple of features missing or not obvious/documented:
- If rendering to a framebuffer - how can i switch back to normal rendering?
- I needed to render GL_FRONT/GL_BACK (CullFace) which is not available in ModernGL
- VertexArrayObjects are bound to a shader program - however in this example I'ld like to apply two different programs to the same geometry (the volume bounding box)
- 1D Textures are not supported (would be sufficient for TransferFunctions - but not crucial)

**Comment by cprogrammer1994** [comment]
1.  `ModernGL.default_framebuffer.use()`

There will be an option to bind arbitrary framebuffer by index (for example QT provided framebuffers)

2.  I will add support for this soon.

3. Create 2 vao using the same vertex buffers

4. Use 2D textures and you can transfer between buffers and textures (PBO)

I am on a phone but I will edit the answer a bit later to dd an example for point 4.

**Comment by ulricheck** [comment]
1. ok - i'll try that

2. I've added workarounds in the example using OpenGL calls directly (@Todo tags in comments).

3. That's what i did - are there any memory or performance drawbacks for this approach?      

4. That's what I did (2d Texture size 256x1xRGBA) - just wanted to let you know a use case for 1D Textures that is not too uncommon. Could you provide an example why copying between buffers could help here?

**Comment by cprogrammer1994** [comment]
3. Pros and cons using two VAOs instead of one:

**pros:**

- VAOs are cheap objects (memory usage).
- You can be sure the vertex attributes are bound properly to the buffers. (otherwise you may need layout qualifiers in both of the shader programs.)
- You create the VAOs once and you will need two render calls only.

**cons:**

- You will need to change the program before each render call (if it was possible, it would require the vertex attributes to be re-bound or at least hinted not to do that)
- Would look more complicated and could be error prone.

[![image](https://user-images.githubusercontent.com/11232402/27760809-f671724e-5e58-11e7-9f25-9103d5ed4e0a.png)](http://www.openglsuperbible.com/2013/12/09/vertex-array-performance/)

> source: http://www.openglsuperbible.com/2013/12/09/vertex-array-performance/
  this post is from 2013 but I guess the results are similar on newer cards as well.

**Comment by cprogrammer1994** [comment]
> 4. Could you provide an example why copying between buffers could help here?

I never implemented a "Volume Raycasting Example", but in case you want to transfer between textures and buffers pixel transfer is a great way. I used 1D textures to store larger then 64KB of data for shaders (UBO was not enough SSBO was not allowed due to OpenGL 3.3 core was the minimum requirement).

**Comment by cprogrammer1994** [comment]
Forgot to mention but `GL_FRONT/GL_BACK` is added to the new version.

Front face can be changed as follows:

```python
ctx.front_face = 'cw'
ctx.front_face = 'ccw'
```
