### ISSUE TITLE
Interactive Examples / Tutorials

### ISSUE THREAD

**Issue by douglasmccormickjr** [moderngl/moderngl#163]
I'm really excited about this wrapper and growth around this project, I've had this on my radar for awhile now.  I was having some issues with the examples/tutorials (I know they aren't quite fleshed out yet)...I had 2 areas/suggestions:

(1) **Could there be an "interactive" example** of some box/object (rendered in ModernGL) that could be resized or moved (depending if you click on the corners to make it larger or you "grab" it from a position to move the location?)  Something that seems a bit more adaptive or responsive to user inputs (by some fashion) would go a long way.  A flat blue triangle is fine but I'm not really sure it helps me understand the expressive or agility of the libraries language/dialect.

(2) **Could there also be a simple "plot" or "graph" creation/example** to see how a list of dates/names and numeric values (or whatever) could be visualized as well...I'm not looking for crazy 3D examples (that might complicate things) but something applicable for data visualization efforts would be nice.

I'll noodle around and see what I can do on my end but any direction or input in these 2 areas would be greatly appreciated.

Thank you again for everything this wrapper can do, **I think its extremely valuable.**

**Comment by cprogrammer1994** [comment]
I will add some 2D and 3D plots for large datasets.
Interactive examples require more code. Resizing a 3D cube by draging its corner require non entry level math or picking. I will try to do my best to keep it as simple as possible.

Embedding ModernGL in PyQt5 directly could lead to simple interactive examples.
The examples currently use a wrapper over multiple window implementations.

**Comment by sfSamuel** [comment]
I looked at all your moderngl examples (not the old-ones). I've the impression, that moderngl is 
much easier to use than OpenGL. After testing "window_tkinter.py" I hoped I would be able to change the example "instanced_rendering_crates.py" so, that it will be integrated in a tkinter GUI (i.e. without PyQt5). 
I thought there must not be so much difference between a 2D and a 3D integration.
I'm still a beginner in Python, and after many hours trials I didn't get it. Earlier I used to develope GUIs and widgets under Windows with Delphi, VC++, c#, VB, but obviously all these experiences were not enough to realize my "plan". 

I know it's an enormous job to write good tutorials, one needs very much time for it. As opengl is still very "young",  it's not easy to find tips/help on the internet. I would wish there were more examples with different GUI frameworks  since the most serious applications need much interaction and configuration. 
I am convinced that opengl is easy to use with GUIs (a s seen in the case of "window_tkinter.py" for 2D), too, but we need some more help (i.e. even if not more tutorials but more examples) when possible.

I think many of us would be ready to upload some good examples if we already had more experience.

**Comment by einarf** [comment]
@sfSamuel People have shared their experiments in #84 

The examples mainly stick to window types that are fully platform independent and requires minimal setup. I think when it comes to additional GUI frameworks we must rely on contributions.

**Comment by sfSamuel** [comment]
Realizing Shader Hooks in moderngl  
I'm new in Python, Opengl and moderngl. As a learning method I try to implement the same tasks with different libraries.  I've seen some glumpy examples and I try to implement them in opengl hence it's a good exercice for me. In the "transform-rotate.py" example in (see the file below)
https://github.com/glumpy/glumpy/blob/master/examples/transform-rotate.py
I met the <transform(position)> expression, but I haven't found any hints for the usage of shader hooks (like <transform>) in moderngl. I can find a workaround (with model/view/Projection) for it, but I would like to know if there is direct way to realize hooks in moderngl?

# -----------------------------------------------------------------------------
# Copyright (c) 2009-2016 Nicolas P. Rougier. All rights reserved.
# Distributed under the (new) BSD License.
# -----------------------------------------------------------------------------
from glumpy import app, gl, gloo
from glumpy.transforms import Rotate

vertex = """
attribute vec2 position;
void main (void)
{
    gl_Position = vec4( <transform(position)>, 0.0, 1.0);
}
"""
fragment = """
void main(void)
{
    gl_FragColor = vec4(1,0,0,1);
}
"""
window = app.Window(width=800, height=800)
@window.event
def on_draw(dt):
    window.clear()
    quad.draw(gl.GL_TRIANGLE_STRIP)
    quad["transform"].angle += 1
quad = gloo.Program(vertex, fragment, count=4)
quad["position"] = [(-.5,-.5), (-.5,+.5), (+.5,-.5), (+.5,+.5)]
quad["transform"] = Rotate(angle=10, origin=(0.5,0.5,0.0))
app.run()
# -----------------------------------------------------------------------------

**Comment by einarf** [comment]
I would guess this is something you can support by adding a new layer on top of moderngl's types. I suspect glumpy is doing a lot of custom parsing of the source code to support this. Maybe it even recompiles and links a new program on the fly if the transform changes?

I guess subroutines are the closest to this in moderngl, but it's not as flexible as these hooks I can imagine.

**Comment by sfSamuel** [comment]
Regarding the shader hooks
Ok, I do not mind if it's not intended to implement the shader hooks in moderngl. 
An additional layer could be an another potential source of error. Keep things as simple as possible. (Sometimes I find that for 5% additional value people invest 300% more work, this should not necessarily be.)
Thank you for the immediate answer.

**Comment by sfSamuel** [comment]
Strange "context.sreen" size after "create_example() call" in tkinter 

I try to migrate moderngl example code with tkinter. In some cases I had no problem, but 
in the case of the example "render_to_texture_example.py" I've got a problem with the 
following methodes when calling them in the following order:
        moderngl.create_standalone_context()                    
        moderngl.create_context()        

This program uses the sreen in order to render the scene to a texture.If in the tkinter init 
function I call the following functions after each other, there will be a context.screen object
(framebuffer(0) object - with instance id = 0 )  object created, but this screen has strange size: 
width = 120, height = 0.  Where do this values come from?

In the original example program at the very beginning of the RenderToTexture:init method  
the context.screen object already exists and it has the size: width = 1424 height = 720.
In the main program the RenderToTexture class will be instanciated by the call run_example() 
and obviously it gets its objects during this call. If you instantiate the RenderToTexture outside 
of the run_example(..) call, the ctx.sreen does not exist at the beginning of the init method.

My first thought was, that in the tkinter "version" probably the window should already exist, 
when the create funtcions will be called, and I tried to put these calls in a button event 
handler function ( befor clicking a button all window creating actions should already be  finished), 
but my assumption was false, noting has changed.
I think one needs better knowledge of what's happening during the run_example call.
Could anybody help me?

When migrating with tkinter the other moderngl examples I did not need the screen object, so the created contex was 
sufficient for my goals. Here below you can see in the twoo very simplified "versions" of render_to_texture_example
demonstrating the ctx.screen size problem.

The original
#==============================
#<render_to_texture_example.py>
#==============================
from window import Example, run_example

class RenderToTexture(Example):
    title = "Render to Texture"
    gl_version = (3, 3)
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        print("<CRenderToTexture::__init__ :  screen.width = {0} ,  screen.height = {1}".format ( self.ctx.screen.width, self.ctx.screen.height) )  
	#....

    def render(self, time, frame_time):
        pass
	#........	

if __name__ == '__main__':
    run_example(RenderToTexture) # here the screen object will be created
    """ after closing the window instantiate the class again """
    d = RenderToTexture() # you can see in the console printout
                          # that 'screen' does not exist
#</render_to_texture_example.py>

#======================================
#<tkinter_render_to_texture_example.py>
#======================================
import moderngl
from window import Example, run_example
import tkinter as tk
from   tkinter import * 
#from tkinter_framebuffer import FramebufferImage 

class RenderToTexture(Example):
    title = "Render to Texture" # not used
    gl_version = (3, 3)
    aspect_ratio = 16/9
    def __init__(self, ctx,  **kwargs): # sfo
        super().__init__(**kwargs)
        pass
        
    def render(self, time, frame_time): # original
        pass
    
#class CWindow_tk(  ):
#class CWindow_tk( Example ):
#class CWindow_tk( tk.Frame ):
class CWindow_tk( tk.Frame, Example ):
    """
    It does not matter from what the class inhereted is:
    """ 
    def btnCreateContext_onClick (self):
        self.ctx3 = moderngl.create_standalone_context()                    
        self.ctx4 = moderngl.create_context()        
        print("CWindow_tk:self.btnCreateContext_onClick : screen.width = {0} , screen.height = {1}".format ( self.ctx4.screen.width, self.ctx4.screen.height) ) 

    def __init__(self, master):
        fraMain_width  = 1290
        fraMain_height =  880
        
        self.ctx0 = moderngl.create_standalone_context()                    
        self.ctx1 = moderngl.create_context()        
        print("CWindow_tk::__init__ : screen.width = {0} , screen.height = {1}".format ( self.ctx1.screen.width, self.ctx1.screen.height) )  
        
        self.fraMain = tk.LabelFrame( master, 
                width  = fraMain_width, 
                height = fraMain_height, 
                text   = "Demonstraing the CREATE_CONTEXT()  CTX.SCREEN SIZE problem ------- Look at the printouts on the console")
        self.fraMain.pack()
                
        self.btnRotateClockwise = tk.Button( self.fraMain, 
                    text    = "Create context by this button ", 
                    command = self.btnCreateContext_onClick )
        self.btnRotateClockwise.pack( side = 'left' )

if __name__ == '__main__':
    root = tk.Tk()
    root.geometry("1300x950+30+30")
    app  = CWindow_tk( root )
    root.title( "The opengl example '"'render_to_texture_example.py'"' integrated with a Tkinter window"  )    
    root.update()
    root.deiconify()
    root.mainloop()
#</tkinter_render_to_texture_example.py>
