### ISSUE TITLE
move moderngl to moderngl organization

### ISSUE THREAD

**Issue by cprogrammer1994** [moderngl/moderngl#297]
this will be done on the next major release

**Comment by cprogrammer1994** [comment]
How can I get https://github.com/cprogrammer1994/ModernGL redirect to the new URL once moved?

**Comment by einarf** [comment]
Github will do this automatically. I saw this recently with the PyWavefront repo after the owner moved it.

https://github.com/greenmoss/PyWavefront -> https://github.com/pywavefront/PyWavefront
https://github.com/greenmoss/PyWavefront/issues/87 -> https://github.com/greenmoss//PyWavefront/issues/87

The only thing I had to do was updating webhooks for Ci integrations and whatnot. Fairly quick and simple.

It will mess up people's forks through because the old repo is kind of still there as a hard fork I think. Not a big deal I think.

**Comment by einarf** [comment]
Updated the previous response quite a bit as it contains some inaccuracies. (In case you are reading this from email)

**Comment by cprogrammer1994** [comment]
I'm thinking about lowercasing the repo name. What do you think?

**Comment by einarf** [comment]
As  long as it doesn't break redirects or forks I don't think it really matters. I guess it's also irrelevant if docs/readme refer to MondernGL or moderngl. I see people using both so it's just about personal taste I guess.

**Comment by cprogrammer1994** [comment]
redirect works :) move is done
