### ISSUE TITLE
Updating default line_width in context vs standalone context.

### ISSUE THREAD

**Issue by Ushk** [moderngl/moderngl#328]
OS: Ubuntu 18.04

Context Version:
ModernGL: 5.5.0
vendor: NVIDIA Corporation
renderer: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2
version: 3.3.0 NVIDIA 430.14
python: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
platform: linux
code: 330

I am trying to move from using a standalone context to a context where I render to window. I am rendering a mesh, and I would like the lines to be wider to increase visibility - however I am  confused by the following:

```
        ctx = moderngl.create_standalone_context()
        ctx.line_width = 4
        print(ctx.line_width) # 4.0
```

```
        self.ctx = moderngl.create_context()
        self.ctx.line_width = 4
        print(self.ctx.line_width) # 1.0
```

Where in the latter case the ctx is being created as in https://github.com/moderngl/moderngl/blob/master/examples/window/pyqt5/window.py

Is there any way to increase the line width when rendering to a window? I can see that 'GL_ALIASED_LINE_WIDTH_RANGE': (1.0, 1.0), which would imply that only lines of thickness 1.0 are supported, but I am then confused as to why it would therefore work in a standalone context.

**Comment by einarf** [comment]
Pretty print `ctx.info` for both of them to get more detailed info.

**Comment by Ushk** [comment]
Thanks for the advice - I removed the 3.3 forward compatible flag, since it wasn't necessary, but the behaviour persisted. With regards to the infos, these were the values that differed: 

WINDOW:   GL_SMOOTH_LINE_WIDTH_RANGE [1.0, 1.0] 	 
STANDALONE:   GL_SMOOTH_LINE_WIDTH_RANGE [0.5, 10.0]

WINDOW:   GL_SAMPLE_BUFFERS 1
STANDALONE:   GL_SAMPLE_BUFFERS 0

WINDOW:   GL_MAX_VARYING_COMPONENTS 0 	 
STANDALONE:   GL_MAX_VARYING_COMPONENTS 124

WINDOW:   GL_MAX_VARYING_FLOATS 0
STANDALONE:   GL_MAX_VARYING_FLOATS 124

This does seem a bit weird, but none of the parameters leaps out as to why it does not accept updating the self.ctx.line_width = 4  . I would understand not accepting a value outside of [0.5,10], but 4.0 doesn't seem to follow. 

I cloned moderngl_window, and had a quick look for anything related to line_width, but nothing leapt out.

**Comment by cprogrammer1994** [comment]
Hi,

Internally a standalone context is created here: https://github.com/moderngl/moderngl/blob/master/moderngl/mgl/internal/opengl/gl_context_linux.cpp

https://github.com/moderngl/moderngl/blob/master/moderngl/mgl/internal/opengl/gl_context_linux.cpp#L86-L101

I hope it helps you find the difference.

**Comment by einarf** [comment]
My diff on OS X between standalone and window.
```
3c3
<  'GL_DOUBLEBUFFER': False,
---
>  'GL_DOUBLEBUFFER': True,
62c62
<  'GL_SAMPLE_BUFFERS': 0,
---
>  'GL_SAMPLE_BUFFERS': 1,
```

This is without making a default framebuffer in standalone.

In both situations:
```
 'GL_SMOOTH_LINE_WIDTH_RANGE': (0.5, 1.0),
```

As far as I know the support for line width is implementation independent and is not required by the spec. It is better to make a simple geometry shader that takes lines and emits triangles (at least what I did in the past)

Some pretty good input advice in the matter here:
https://www.reddit.com/r/opengl/comments/at1az3/gllinewidth_not_working/

**Comment by Ushk** [comment]
Apologies for the delay in replying and thanks for the post @einarf! It isn't intuitive to me why there would be a difference between standalone and window on one OS but not on another, and I couldn't see anything in the C++ code that would give rise to a difference, but it's probably getting too far into the weeds at this point. At least to me it would make sense if the behaviour was consistent between the two methods, but differed between OSs - or am I missing something? This is purely academic at this point, I will go down the triangles route, I was just curious.

**Comment by einarf** [comment]
I did some spec reading and I think I understand what is going on.

---
## OpenGL 4.6  (Compatibility Profile) - February 2, 2019

### E.2.1 Deprecated But Still Supported Features

The following features are deprecated, but still present in the core profile.  They may be removed from a future version of OpenGL, and are removed in a forward-compatible context implementing the core profile.

* Wide lines -LineWidth values greater than 1.0 will generate an INVALID_-VALUE error.
* Global  component  limit  query  -  the  implementation-dependent  values MAX_VARYING_COMPONENTS and MAX_VARYING_FLOATS.
* The query targets NUM_COMPRESSED_TEXTURE_FORMATS and COMPRESSED_TEXTURE_FORMATS (see section 8.5).
* Bitmap pack/unpack state for bitmaps - the pixel pack parameters UNPACK_LSB_FIRST and PACK_LSB_FIRST.
---

I got the same result as you on win10. The headless context I get from the OS is actually a core context stripping away all compatibility. This is why `MAX_VARYING_COMPONENTS ` and `MAX_VARYING_FLOATS` are 0 (They are no longer relevant) and line width reports 1.

Window libraries like qt, pyglet etc do a lot more initialization to ensure the user gets a context with compatibility profile (unless you are on OS X). The reasons for my initial test is that OS X only support forward compatible core contexts. The missing `GL_SAMPLE_BUFFERS` and `GL_DOUBLEBUFFER` is simply because they refer to the default framebuffer that did not exist in standalone.

**Comment by einarf** [comment]
@cprogrammer1994 There might actually be an argument to remove `GL_MAX_VARYING_COMPONENTS` 
`GL_MAX_VARYING_FLOATS`. As far as I know they are irrelevant since 3.2 core.

**Comment by cprogrammer1994** [comment]
should I wrap [this](https://github.com/moderngl/moderngl/blob/master/moderngl/mgl/limits.cpp#L96) with an extra if to check if we have OpenGL 4.4-?
same for `GL_MAX_VARYING_COMPONENTS`

**Comment by einarf** [comment]
I think that would remove confusion in the future

**Comment by einarf** [comment]
`GL_MAX_VARYING_COMPONENTS` and `GL_MAX_VARYING_FLOATS` removed in 4.4+ in commit https://github.com/moderngl/moderngl/commit/bf1815023f653ab744f37460d6f9c33df92f1856

As far as I know everything related to this issue is resolved. Feel free to reopen if this is not the case 😃
