### ISSUE TITLE
copying buffer / trying to render to texture and screen again

### ISSUE THREAD

**Issue by pavelkrupala** [moderngl/moderngl#338]
Hello,
I'm trying to render to a texture and render to screen again (hopefully just once). However I tried 2 versions and at both I failed:
A) RTT, copy to screen
B) RTT, render to screen

min code:
```
self.vao = self.ctx.vertex_array(self.prog2, self.vao_content, self.ibo)
size = (1024, 1024)
self.texture = self.ctx.texture(size, components=3, dtype='f1')
depth_attachment = self.ctx.depth_renderbuffer(size)
self.fbo1 = self.ctx.framebuffer(self.texture, depth_attachment)

#render method A
self.fbo1.use()
self.vao.render()
self.ctx.detect_framebuffer().use()
self.vao.render()
self.ctx.finish()

#render method B
self.fbo1.use()
self.vao.render()
#self.ctx.detect_framebuffer().use()
self.ctx.copy_framebuffer(self.ctx.screen, self.fbo1)
self.ctx.finish()
```

Is there something obvious I do miss?

**Comment by McSinyx** [comment]
To render to screen, you should use the screen, i.e. `self.ctx.screen.use()`, before rendering. You might also need to clear the rendering target before rendering but I'm not very certain about that.

**Comment by pavelkrupala** [comment]
I've tried that and it should be working unless you spawn that in in pyqt5 window. however for PyQt5, after some more digging, this is working (found at pyqt5_window.py example):
```
class MyWidget(QModernGLWidget):
    def render(self):
        self.screen.use()
```

**Comment by einarf** [comment]
If you can use moderngl_window, it will probably save you from a lot of hassle.

**Comment by pavelkrupala** [comment]
Hi einarf, thanks. Unfortunatelly I can't, but I'm checking that code a lot if I do something too differently.

**Comment by cprogrammer1994** [comment]
sometimes QT's default framebuffer is not 0
use self.ctx.detect_framebuffer() once when the window is created and QT lets you draw the first time.
I usually see fbo=1 there, I assume QT creates a framebuffer for the user by default
Some old examples have this.
We implemented `detect_framebuffer` because of QT.

PS:
if you create a moderngl context for QT. make sure it was created in the render() not somewhere else.
I mean QT have some init function (it does not bind the framebuffer QT provides as the default)
If you create the moderngl context in render. ModernGL will detect QT's default fbo and let you use it through ctx.screen
