### ISSUE TITLE
vao_content definition ambiguity

### ISSUE THREAD

**Issue by francoisruty** [moderngl/moderngl#340]
Here is an example of a vao_content definition

```python
vao_content = [
    # 2 floats are assigned to the 'in' variable named 'in_vert' in the shader code
    (vbo, '2f', 'in_vert')
]
vao = ctx.vertex_array(prog, vao_content, ibo)
```

We specify 2 floats for the shader variable `in_vert`, even if the shader code says `in_vert` is a `vec3` (instead of a `vec2`)

This was a typo on my side but it would be nice if there was some kind of sanity check.

**Comment by cprogrammer1994** [comment]
thank you for the issue. this is a feature rather than a bug added during 5.x

It comes handy when you have color or texture coordinates.
it is possible to bind only the rgb components and leaving alpha to detault to 1.0
it is possible to bind only texture coordinates xy in a shader that support xyz texture coordinates, z will default to 0.0

In the next major version it will be possible to bind buffers in complex vertex arrays without explicitly specifying the buffer formats.

it will be:

```py
vao = ctx.vertex_arrayprog, [
   vbo1.bind('in_vert'),
   vbo2.bind('in_color', 'in_texture', layout='3f 2f'), # explicit layout is required when size or format differs on purpose
])
```

**Comment by francoisruty** [comment]
all right!

**Comment by cprogrammer1994** [comment]
I forgot about the `detect_format`

https://github.com/moderngl/moderngl/blob/d60d9ce1212967091b049a52152b3fb5a73aa582/moderngl/program.py#L118-L129

append a ` /i` to it for per instance attributes. -- there are no better alternatives for moderngl 5.x I could think of.
