### ISSUE TITLE
Graceful fallback for render_indirect

### ISSUE THREAD

**Issue by lordmauve** [moderngl/moderngl#346]
Trying to make a ModernGL-based game on Mac OS it appears it is possible to request an OpenGL 4.1 context or a 3.3 context. However, that `vertex_array.render_indirect()` crashes with a segfault. I believe this is NULL if the feature is unsupported?

I was able to mostly work around this by calling `vertex_array.render()` repeatedly instead.

However, the ability to pass base_vertex is missing, ie. `glDrawElementsInstancedBaseVertexBaseInstance()` is not exposed.

It would be useful if ModernGL could automatically fall back to this path, which would be much faster than doing it in Python. Otherwise, it would be useful to detect if `render_indirect()` is not going to be supported at all as this will let me handle this case in Python.

**Comment by smishlayev** [comment]
$ python -m moderngl
moderngl 5.5.3
--------------
vendor: Intel Inc.
renderer: Intel HD Graphics 5000 OpenGL Engine
version: 4.1 INTEL-10.14.74
python: 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]
platform: darwin
code: 410

**Comment by einarf** [comment]
This is a problem for macos being limited to GL 4.1. I checked the extensions as well for intel/nv/ati/apple. They usually match up 100% on capabilities and the following extensions are not there.

```
ARB_multi_draw_indirect
ARB_base_instance

4.3 core glMultiDrawArraysIndirect
4.3 core glMultiDrawElementsIndirect
4.2 core glDrawArraysInstancedBaseInstance
4.2 core glDrawElementsInstancedBaseVertexBaseInstance
```
On OS X we only have
```
4.0 core glDrawArraysIndirect
4.0 core glDrawElementsIndirect
```

`render_indirect` are using the `MultiDraw*` core 4.3 functions. I'm wondering if it might be possible to provide a method for 4.0 as well. The sad part is that OS X would then not support instanced rendering with indirect rendering.

Maybe 6.x can at least support the 4.0 version? This would maybe be more correct?
```
# 4.0 version
VertexArray.render_indirect
# 4.3 version
VertexArray.render_indirect_instanced
```

**Comment by einarf** [comment]
A quick solution for now is to check the `ctx.version_code` property.
https://moderngl.readthedocs.io/en/stable/reference/context.html#moderngl.Context.version_code

I'll can add some comments in docs for 5.5 and 5.6.

**Comment by einarf** [comment]
Also : OS X contexts are simple. If you have OS X Mavericks (version 10.9) from 2013 and the hardware to support 4.1 you will get a 4.1 context. There is no in-between. I personally assume 4.1 core for my projects when `darwin` is the platform.

**Comment by lordmauve** [comment]
I guess it would not be too expensive for render_indirect function (and indeed, other functions) could test for version/extension support and raise NotImplementedError if missing, rather than segfaulting?

**Comment by lordmauve** [comment]
Ah, I think I was reading this and expecting it to work under OpenGL 4.1. ![Screenshot_20190917_214519](https://user-images.githubusercontent.com/617224/65080024-478a1980-d998-11e9-9629-eb4840dbfd45.jpg)

**Comment by einarf** [comment]
That would definitely the ideal solution It means we have to query for extensions `glGetStringi(GL_EXTENSIONS, k)` / `GL_NUM_EXTENSIONS ` and store a prepared `dict` in the context. 

Exposing that dict to python is probably also a good idea through `Context.extensions` like the current `info` property : https://moderngl.readthedocs.io/en/stable/reference/context.html#moderngl.Context.info

Then I guess the C++ code would have to look up these values for at least the 4.1+ methods. I think that's the only way to query that accuratly because 4.1 contect can potentially support 4.2 and 4.3 core stuff thought extensions. Just like macos do support `GL_ARB_internalformat_query` and `GL_ARB_texture_storage` (both 4.2 core) through extensions in the 4.1 context.

**Comment by einarf** [comment]
Ah right. `ARB_multi_draw_indirect` and `ARB_base_instance` are listed there as extensions. They are then optional and not part of `core`. They get moved to into core 4.2 and 4.3 later.

**Comment by einarf** [comment]
The good news is that we just started a small project to extract this kind of information:
https://github.com/moderngl/opengl-registry

**Comment by cprogrammer1994** [comment]
It would be possible to use the `glDrawArraysIndirect` and the `glDrawElementsIndirect` but it would break backward compatibility since the struct size in `glDrawArraysIndirect` is just 16 bytes and not 20 bytes. (stride=20 | what we pass for the `glMultiDrawArraysIndirect` in the code below)

https://github.com/moderngl/moderngl/blob/d630f3bbc5800e77d8b65c9a2cbd62efce14218c/moderngl/old/VertexArray.cpp#L326-L330

**Comment by cprogrammer1994** [comment]
Adding an extra parameter to expose `stride` will not break backward compatibility.
When stride is 20 for indexed, 16 for simple render, we can use the non `glMulti...` calls.

In moderngl 6 we will use the non `glMulti` calls. Unfortunately stride will not be exposed in next.

In moderngl 6 `vao.indirect_buffer = ...` will be taken into account when `vao.render()` is called.
This means that stride would be harder to expose.

**Comment by szabolcsdombi** [comment]
Closing this as being a bit outdated.

for Windows and Linux it is safe to say you can have indirect draw.
for OSX you might want to run it using ANGLE as OpenGL is deprecated anyways. -- this will soon be available as an example once the GLES support is fully implemented.
