### ISSUE TITLE
Using ModernGL in a web server context

### ISSUE THREAD

**Issue by evancasey** [moderngl/moderngl#388]
Hi there! Thanks for all the work you've put into this project, really great stuff.

Is it possible to use ModernGL in a python webserver (i.e. Flask)? I would like to build a service that accepts a request with an image in it, uses ModernGL to do some transformations, and then returns the output over HTTP. Are there any examples of how to do this?

**Comment by einarf** [comment]
I guess the best way is to have a worker process for this, If you can create a headless context with x11 or egl + xvfb with a sample script it should be more than possible. The worker process can create the context on initialization and wait for jobs.

I haven't used flask much, but I have played with this using django and celery.

**Comment by cprogrammer1994** [comment]
an OpenGL context can be used from one thread at a given time.
turn off threads in flask/werkzeug/waitress/... (the module that serves the flask app).
you don't have to give up on threads you can always scale up the number of processes: for example docker can scale up single threaded flask app containers nicely.
Threads in python don't run parallel since there is the GIL. if you still want to use a threaded flask app make sure to call `context.enter()` and maybe `.leave()` after processing a request

It is possible `context.enter()` is named differently what you really need is just a glxMakeCurrent/wglMakeCurrent/eglMakeCurrent and a "critical section" while rendering.

**Comment by evancasey** [comment]
Thank for the tips! Will try this and report back.

**Comment by einarf** [comment]
Closing this for now. Be free to reopen if you have feedback or updates!
