### ISSUE TITLE
Releasing objects

### ISSUE THREAD

**Issue by christopherhesse** [moderngl/moderngl#409]
It looks like moderngl requires explicitly releasing at least some types of objects.  I expected that the object would be automatically released when the reference count dropped to zero.  I didn't see any mention of when releasing is required in the docs, should that be added?

Should I define `__del__` functions on my objects and make sure to call all `.release()` methods on every moderngl object?

**Comment by einarf** [comment]
Sorry for late reply. Yes, this is a challenge with moderngl and how to approach it depends on your use case. It's not as straight forward as just releasing the resource. If you throw in shared context and external libaries also using the resources moderngl creates it gets pretty hairy. The current way it works is the most flexible, but the problem is that it takes a lot of people by surprise. That is a problem.

I'm looking into adding a configurable gc mode in the context so people will have options. This was experimented with in another branch (`next`).

**Comment by christopherhesse** [comment]
Great!  Yeah, in the absence of a better gc mode, a docs section about this would be very handy.  Especially if it included examples for common use cases.  Before I filed this issue, I had just spent a few hours going back and forth with a user who was experiencing a memory leak with my app.

Even once we realized that the issue was my opengl code, I sort of had to guess and check to figure out what the correct fix was since I was unable to figure out the solution from the docs alone (at least the parts I read).

**Comment by einarf** [comment]
Doing a release tomorrow tomorrow probably. I'll try to add a section in docs about this.

**Comment by einarf** [comment]
Documented : https://moderngl.readthedocs.io/en/latest/the_guide/gc.html

**Comment by christopherhesse** [comment]
Great thanks!

**Comment by einarf** [comment]
Experiment going on here : https://github.com/moderngl/moderngl/issues/444
