### ISSUE TITLE
ResourceWarning for unreleased objects

### ISSUE THREAD

**Issue by tpwrules** [moderngl/moderngl#431]
**A simple use-case of the new feature**

The documentation mentions the fact that some objects must be released using their `release()` method before deleting them to avoid leaking the underlying OpenGL objects, but it is easily possible users to miss that and write a program which does not release objects. Furthermore, the program may intend to release objects, but have bugs which cause objects be deleted without being released under certain circumstances.

Python has a `ResourceWarning` designed to warn when resources may be leaked. It could tell users where objects are leaked so they can fix the problem.

**Describe the solution you'd like**

I understand that it may not be safe to release an object during deletion. I think objects that need to be released should instead be given a default `__del__()` method which issues a `ResourceWarning` if the object is not released at the time of deletion.

I can see two potential problems:
1. During interpreter shutdown, all objects will be automatically deleted. It's okay if objects are not properly released because the OpenGL driver will release them once the program exits, so a warning would be a false positive. This could be worked around by not emitting a warning if `sys.is_finalizing()` returns `True`.
2. If the object being deleted does not own the underlying OpenGL object, then the warning is a false positive because there exists another object which can still be used to release the OpenGL object. I'm not sure if it is possible to create such objects. If not, then this is not a problem. Otherwise, this feature may cause excessive false positives in some programs.

I can submit a PR to implement this feature if it would be helpful.

**Comment by einarf** [comment]
This might not be a bad idea, but there are some challenges:

Some examples:
* Creating and destroying contexts in headless mode will force the user to `release()` everything before deleting the context to avoid resource warning
* pyqt5 really loves to destroy contexts randomly. Especially when docking and undocking widgets. Sometimes shared objects are supported but you still need to recreate the container objects.

Users can end up in a situation were they cannot call `release()` because a crash might happen. If they gc the object they will get a resource warning. One idea in the past was attempting to switch to the context the object was created. If unsuccessful we could assume the object was deleted, but this doesn't work well when objects are shared between contexts.

**Comment by tpwrules** [comment]
I didn't know that `release()` might crash in some circumstances. How would I tell before calling it that it might crash? Is this something the code can tell?

If it's that the context doesn't exist, is trying to switch to it the only way? Is there no way to get some notification or do some query about whether or not a context has been destroyed?

I'm not familiar with OpenGL's object model yet.

**Comment by einarf** [comment]
Working on garbage collection : https://github.com/moderngl/moderngl/issues/444

Would be there are room for a `ResourceWarning` here, but not 100% sure.

**Comment by einarf** [comment]
We could add a "warn" mode in `Context.gc_mode`, but I'm not sure how useful that is now.
