### ISSUE TITLE
"the first vertex attribute must not be a per instance attribute" Error

### ISSUE THREAD

**Issue by dawid-januszkiewicz** [moderngl/moderngl#451]
**Description**

`the first vertex attribute must not be a per instance attribute` Error is raised when binding/declaring a vao only containing vbos with the per-instance format endings '/i'

**Proof of code**

```py
vao_content = [
    (color_buffer, '3f/i', 'in_color'),  # first buffer
    (verts_buffer, '2f/i', 'in_verts'),
]
```

**Version info**

```
moderngl 5.6.4
--------------
vendor: AMD
renderer: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.11.2-arch1-1, LLVM 11.1.0)
version: 4.6 (Core Profile) Mesa 20.3.4
python: 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0]
platform: linux
code: 460
```

**Comment by einarf** [comment]
Thank you. We talked about this on Discord and it **might** be possible to remove this restriction since we do support empty VertexArray now. It all relies on if GL acceps `vertices=N` as the base geometry that will be instanced. This could be used in interesting ways combining `gl_VertexID` and `gl_InstanceID`.

**Comment by szabolcsdombi** [comment]
this will be fixed in the next release

https://github.com/moderngl/moderngl/pull/484

**Comment by szabolcsdombi** [comment]
fixed merged
