### ISSUE TITLE
Installing from source fails to build the moderngl.mgl file

### ISSUE THREAD

**Issue by stirlingboy69** [moderngl/moderngl#454]
**Description**
Hello,

I've download moderngl from git and typed
'python setup.py install' . No errors were reported during the build, but
when I run a python shell and import moderngl I get the following error:

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\projects\python\moderngl-master\moderngl\__init__.py", line 6, in <module>
    from .buffer import *
  File "c:\projects\python\moderngl-master\moderngl\buffer.py", line 2, in <module>
    from moderngl.mgl import InvalidObject  # type: ignore
ModuleNotFoundError: No module named 'moderngl.mgl'**

I am on
Windows 10 Pro,
Python 3.7.4
Visual Studio 2017

Thanks.

**Proof of code**

```py



```

**Expected behavior**

**Version info**

```



```

**Comment by einarf** [comment]
You might have better success with `pip install -e .` or `pip install .`?

**Comment by einarf** [comment]
I think I finally understand whay you are doing here. It does't matter if you use `pip` or `python setup.py install`. You installed moderngl from source, but are still located inside the moderngl directory causing python to use the source instead of the installed package.

If you move out of the moderngl directory it should work, If you want use the source directory in development mode you need to `pip install -e .` and build the extension with `python setup.py build_ext -i`.

**Comment by einarf** [comment]
Closing this for now assuming what mentioned in the above post is the solutuon.

Be free to re-open if this is still not resolved.
