### ISSUE TITLE
Add glMemoryBarrier

### ISSUE THREAD

**Issue by Rafale25** [moderngl/moderngl#499]
**A simple use-case of the new feature**
B O I D S

glMemoryBarrier(GL.GL_SHADER_STORAGE_BARRIER_BIT);
^
this at least or the BOIDS will come while you sleep

**Comment by einarf** [comment]
Yep. We definitly  saw the need for this in a discusstion on discord. When having to dispatch multiple CS calls doing some sorting algos it would be conveinent rather than importing PyOpenGL.

The `ComputeShader.run` function could support a `memory_barrier: bool` argument that would call `glMemoryBarrier(GL_SHADER_STORAGE_BARRIER_BIT);` after execution and/or a `Context.memory_barrier` property to conver more complex use cases.

It's a fairly small small thing, but the question is if we should supply the enums or not.

**Comment by compik710** [comment]
I also need a memory barrier, but unfortunately I don't know how to work with repository code :sweat:

**Comment by einarf** [comment]
You can call it just fine using pyopengl for now.
