### ISSUE TITLE
Large number of standalone context creation fails

### ISSUE THREAD

**Issue by abey79** [moderngl/moderngl#575]
**Description**

Testing ModernGL-based project might entail creating a standalone context many times, once for each test case. It appears that ModernGL fails after a number of context creation, at least on macOS Ventura / M1 max, which makes large test runs fail.

**Proof of code**

```py
import moderngl

for i in range(1000):
    if (i % 50) == 0:
        print(f"iteration {i}")
    ctx = moderngl.create_context(standalone=True)
    del cix
```

Generated output:
```
iteration 0
Context leak detected, msgtracer returned -1
iteration 50
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
iteration 100
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
iteration 150
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
iteration 200
Context leak detected, msgtracer returned -1
Traceback (most recent call last):
  File "/Users/hhip/Library/Application Support/JetBrains/PyCharm2022.3/scratches/scratch_11.py", line 6, in <module>
    ctx = moderngl.create_context(standalone=True)
  File "/Users/hhip/Library/Caches/pypoetry/virtualenvs/vpype-l5n3HO8W-py3.10/lib/python3.10/site-packages/moderngl/context.py", line 1622, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/Users/hhip/Library/Caches/pypoetry/virtualenvs/vpype-l5n3HO8W-py3.10/lib/python3.10/site-packages/glcontext/__init__.py", line 100, in create
    return darwin.create_context(**_strip_kwargs(kwargs, ['mode']))
Exception: cannot create OpenGL context
```

**Version info**

```
moderngl 5.8.1
--------------
vendor: Apple
renderer: Apple M1 Max
version: 4.1 Metal - 83
python: 3.10.10 (main, Feb 14 2023, 17:01:47) [Clang 14.0.0 (clang-1400.0.29.202)]
platform: darwin
code: 410
```

**Comment by szabolcsdombi** [comment]
Hi, as I remember we do not rely on `__del__` for resource handling. we have a .realease() method in most cases.
We also have some stress test in the utils. I get back with a more detailed answer when my time allows it.

**Comment by abey79** [comment]
Right. My including of `del ctx` is pointless anyway, as it as not additional effect since `ctx` is reassigned.

Adding `ctx.release()` solves the issue:

```python
import moderngl

for i in range(1000):
    if (i % 50) == 0:
        print(f"iteration {i}")
    ctx = moderngl.create_context(standalone=True)
    ctx.release()
```

Output:
```
iteration 0
iteration 50
iteration 100
iteration 150
iteration 200
iteration 250
iteration 300
iteration 350
iteration 400
iteration 450
iteration 500
iteration 550
iteration 600
iteration 650
iteration 700
iteration 750
iteration 800
iteration 850
iteration 900
iteration 950
```

I'll let you close the issue unless you feel there is something to be done still, may be a note in the docs?

**Comment by szabolcsdombi** [comment]
Related docs page: [manually-releasing-objects](https://moderngl.readthedocs.io/en/latest/topics/gc.html?highlight=release#manually-releasing-objects)

Some notes that pop into my mind:

- We do not use `__del__` due to it is not reliable and it can be entirely prevented with a dangling ref to the object. The simplest I can think of is storing context in it's `extra` field.

- Most of the ModernGL objects hold a ref to the context mostly to have access to the gl calls. Without properly implementing tp_traverse the GC won't find the island of dead objects just by loosing all the refs from the main code.

- `__del__` might be called without having an active gl context making a fault when calling opengl functions.

- some objects cannot be released, for example when the OpenGL context was lost or destroyed by the window.
