### ISSUE TITLE
Requested OpenGL version 330, got version 300

### ISSUE THREAD

**Issue by hariharan382** [moderngl/moderngl#584]
I am trying to use simple_3dx library, it is complaining """Requested OpenGL version 330, got version 300""" error

python -m moderngl -->
OUTPUT:
moderngl 5.8.2
--------------
vendor: NVIDIA Corporation
renderer: Quadro P1000/PCIe/SSE2
version: 3.3.0 NVIDIA 470.182.03
python: 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0]
platform: linux(20.04)
code: 330

opengl version -->
OUTPUT:server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.6.0 NVIDIA 470.182.03
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 470.182.03
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 470.182.03
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_group_vote, GL_EXT_shader_implicit_conversions, 

any idea on why this error pops up?

**Comment by einarf** [comment]
Can you share any code here? I don't even know what you are doing. You are trying to detect a context created by this library? Need a lot more information here.

**Comment by hariharan382** [comment]
I am following the basic tutorial in docs, that's it

**Comment by szabolcsdombi** [comment]
maybe the window does not require a high OpenGL version and the system provides a 3.0.
https://github.com/angeloskath/simple-3dviz/blob/master/simple_3dviz/window/wx.py#L40-L43

**Comment by einarf** [comment]
Mabe a bug in the [simple-3dviz](https://github.com/angeloskath/simple-3dviz) project?

**Comment by hariharan382** [comment]
> Mabe a bug in the [simple-3dviz](https://github.com/angeloskath/simple-3dviz) project?

I need to find light intensity incident on the object, visit possible to compute in simple_3dviz , or any other library

**Comment by einarf** [comment]
Asking again: Can you create an issue in the [simple-3dviz](https://github.com/angeloskath/simple-3dviz) project and link this one?

You are not providing much information here, so I don't think it's possible to progress here. The other project probably have a better idea what the problem is. It's WX creating the context, not moderngl.. so It's not really moderngl related at all.

**Comment by hariharan382** [comment]
https://github.com/angeloskath/simple-3dviz/issues/1


I tried this solution, but it seems the issue with moderngl....

**Comment by szabolcsdombi** [comment]
it is not really possible as moderngl is not involved in the opengl context creation.

you can simply check the version by placing this code right before the moderngl.create_context is called:

`from OpenGL import GL; GL.glGetString(GL.GL_VERSION)`

you might need to pip install pyopengl for the code above to work

**Comment by szabolcsdombi** [comment]
to understand better the problem you should know that:

- in order to have OpenGL available to load, there must be a window and opengl context created.
- when a window is created it must select a pixel format and create an OpenGL context.
- at this point the OpenGL functions are already tight to a version and driver implementation.

the above happens without moderngl being present

- moderngl is a library using the OpenGL methods provided by glcontext.
- glcontext is a very simple module, in your case it just loads the already existing OpenGL methods and pass it to moderngl. (glxGetProcAddr and similar)
- moderngl calls glGetIntegerv for the major and minor versions and finds `3` and `0` respectively.
- at this point there is no way to get a higher version by calling any other gl methods.

---

to fix the issue you should check the gl version with the snippet pasted above right after the window creation and tweak the window creation parameters until you get your `4.6.0 NVIDIA 470.182.03` version reported.

PS: if you use X11 forwarding you might not get it unless setting `LIBGL_ALWAYS_INDIRECT` properly.
