### ISSUE TITLE
Feature request: Multiple shader sources per shader stage

### ISSUE THREAD

**Issue by cromachina** [moderngl/moderngl#601]
It would be nice to be able to specify multiple shaders per stage, such as if one wanted to include a shader library without annoying text manipulation. I think the most flexible thing to do would be allowing the creation of shader objects, which are then passed to the program.

This would possibly look like the following:
```py
vert_shader = self.ctx.vertex_shader(pathlib.Path('render.vert').read_text())
frag_shader = self.ctx.fragment_shader(pathlib.Path('render.frag').read_text())
frag_library_shader = self.ctx.fragment_shader(pathlib.Path('noise.glsl').read_text())
program = self.ctx.program(shaders=[vert_shader, frag_shader, frag_library_shader])
```

**Version info**

```
moderngl 5.8.2
--------------
vendor: NVIDIA Corporation
renderer: NVIDIA GeForce GTX 980 Ti/PCIe/SSE2
version: 3.3.0 NVIDIA 532.03
python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
platform: win32
code: 330
```

**Comment by szabolcsdombi** [comment]
Help me understand this use case better by providing a link to an article or an example that uses multiple sources per shader stage.

I know there is an option to pass multilpe shader sources for a single Shader Object. [link](https://www.khronos.org/opengl/wiki/Shader_Compilation#Shader_object_compilation).

The documentation states:

```c++
glShaderSource(GLuint shader​, GLsizei count​, const GLchar **string​, const GLint *length​);
```

This function takes the array of strings, given by string​ and stores it into shader​. Any previously stored strings are removed. When the shader is compiled, it will be compiled as if all of the given strings were concatenated end-to-end.

I also found that:

```c++
glAttachShader(GLuint program​, GLuint shader​);
```

Note: It is possible to attach multiple shader objects for the [same shader stage](https://www.khronos.org/opengl/wiki/Shader) to a program. This is perfectly legal. When linking them, all of the code will be combined. However, only one of those shader objects can have a main function. Linking like this will work very much like linking multiple object files in a C/C++ program: one .cpp file can call code in another .cpp file if it has forward declarations of functions. So you can have "libraries" of functions that individual shaders can choose to use.

**Recommendation: That being said, while this power is available, it is best not to use it. It usually works, but because most OpenGL applications don't do this, it doesn't get as thoroughly tested as other parts of the OpenGL API. So you're likely to run into more driver bugs this way. Generally stick to having one shader object per shader stage.**

---

As I can see neither options provide any benefit over:

```py
vert_shader = pathlib.Path('render.vert').read_text()
frag_shader = pathlib.Path('render.frag').read_text()
noise = pathlib.Path('noise.glsl').read_text()

program = ctx.program(
    vertex_shader=vert_shader,
    fragment_shader=''.join([noise , fragment_shader]),
)
```

---

I almost always share code between multiple programs and multiple shader stages.

My use cases usually include the following:

- sharing the uniform buffer layout definition between the vertex and fragment shader (
- sharing utility functions between different shader programs (qtransform, noise functions, ...) ([example](https://github.com/szabolcsdombi/zengl/blob/main/examples/rigged_objects.py#L119-L123))
- sharing material definition and material calculations between different fragment shaders
- exposing precalculated kernels, arrays, constants without manually typing them into glsl ([example](https://github.com/szabolcsdombi/zengl/blob/main/examples/blur.py#L9-L17))

For the first and last option attaching multiple shader objects to a single program object does not help.

---

I was planning to add include support to ModernGL. I successfully tested it within ZenGL and I think I found a really nice way to do it. [Here you can find how it works in ZenGL](https://zengl.readthedocs.io/en/latest/#shader-includes).
Recenlty I have updated the "program" object to allow overriding the default include lookup table. This is necessary for programs that want to use the includes but do not want to override global state. (I used to have debug renderers inserted into a larger application and those often share an ubo definition).

---

Would includes solve the problem you want to solve?

**Comment by szabolcsdombi** [comment]
Thank you for the feedback. I think I can add this feature soon to moderngl. I have to first check if it could break anything for the existing users. I doubt it but I still have to be careful as this feature requires touching a part that every moderngl user uses.

**Comment by szabolcsdombi** [comment]
https://github.com/moderngl/moderngl/pull/602
