### ISSUE TITLE
Subroutine uniforms do not appear in `Program` members

### ISSUE THREAD

**Issue by mugulmd** [moderngl/moderngl#603]
**Description**

I am trying to modify the value of a subroutine uniform variable from a python script using moderngl, however this uniform doesn't seem to be found in the program's `_members` dict. However its name is found in `subroutines`, so I'm guessing subroutine uniforms are not completely ignored.

**Proof of code**

Fragment shader:
```
#version 460

uniform vec2 resolution;
uniform float time;

out vec3 frag_color;

subroutine float noise_gen(vec2 p);

subroutine(noise_gen) float wave(vec2 p) {
    return abs(sin(2*p.x + 9*p.y) * cos(5*p.x - 11*p.y));
}


subroutine(noise_gen) float rand(vec2 p) {
    return fract(sin(dot(p, vec2(75.214, 983.13))) * 43758.5453123);
}

subroutine uniform noise_gen noise;

void main() {
    // Retrieve, normalize and unsqueeze fragment coordinates
    vec2 uv = gl_FragCoord.xy / resolution;
    uv = 2.0 * uv - 1.0;
    uv.x *= resolution.x / resolution.y;

    float red = noise(uv);
    red *= abs(sin(time));

    frag_color = vec3(red, 0., 0.);
}
```

Test script:
```py
self.program = self.load_program(
    vertex_shader=ClaudeApp.vertex_shader,
    fragment_shader=ClaudeApp.fragment_shader
)
print(self.program._members)
print(self.program.get('noise', None'))
print(self.program.subroutines)
```

Result:
```
{'in_vert': <Attribute: 0>, 'resolution': <Uniform: 0>, 'time': <Uniform: 1>, 'wave': <Subroutine: 0>, 'rand': <Subroutine: 1>}
None
('noise',)
```

**Expected behavior**

I would expect to see the `noise` uniform in the `_members` dict and be able to access it with `program.get`.

**Version info**

```
moderngl 5.8.2
--------------
vendor: Intel
renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
version: 4.6 (Core Profile) Mesa 21.2.6
python: 3.11.3 (main, Apr  5 2023, 14:15:06) [GCC 9.4.0]
platform: linux
code: 460
```

**Comment by szabolcsdombi** [comment]
Setting subroutines are broken or partially broken.
They are not reliable even when the OpenGL code is implemented perfectly.
This is due to the lack of their use in everyday projects. Drivers fail to implement them right.
Also they require OpenGL 4.0+ and not faster than a switch case.
ModernGL make use of calling glUseProgram() for uniform handling.
The spec says subroutines must be set again and again after every glUseProgram that follows at least one render call.
They do not persist as normal uniforms would.

Curious ModernGL users may find subroutines just because they see we support/supported them.
This gives them confidence to actually use it.

I mark this as won't fix. I already removed subroutines from the documentation.
I won't remove any implementation that handles uniforms, so if you are using it right now, it won't break your code.
But is highly likely it is also not working reliably.

I am sorry for this.
