### ISSUE TITLE
How to Request the High Performance GPU to Accelerate Rendering

### ISSUE THREAD

**Issue by ncheng89** [moderngl/moderngl#643]
Hello, my Linux system is an ubuntu system with two graphics cards. I specified the headless backend according to the documentation, but I found that it did not call the gpu resources, but still used the cpu resources. I guess there should be no The call is successful, so how should I call it? Can I specify which graphics card resource to use?

```sh
root@554fda42bf96:/opt/ms_rtmp/gltest# python3 d.py  
Vendor: Mesa/X.org
Renderer: llvmpipe (LLVM 11.0.1, 256 bits)
OpenGL version: 4.5 (Core Profile) Mesa 20.3.5
ModernGL version: 5.9.0
root@554fda42bf96:/opt/ms_rtmp/gltest# nvidia-smi 
Wed Jan  3 15:59:15 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
|  0%   58C    P8    15W / 285W |    195MiB / 12282MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:05:00.0 Off |                  N/A |
|  0%   47C    P8     8W / 285W |    195MiB / 12282MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
root@554fda42bf96:/opt/ms_rtmp/gltest# cat d.py 
import moderngl

#ctx = moderngl.create_standalone_context()
ctx = moderngl.create_context(standalone=True, backend='egl')
print("Vendor:", ctx.info['GL_VENDOR'])
print("Renderer:", ctx.info['GL_RENDERER'])
print("OpenGL version:", ctx.info['GL_VERSION'])
print("ModernGL version:", moderngl.__version__)
root@554fda42bf96:/opt/ms_rtmp/gltest# 
```

**Comment by compik710** [comment]
ModernGL does not have functionality for selecting a video card, as it is limited to the functionality of the OpenGL API.
If you need to use Nvidia GPU instead of CPU's iGPU, you can try adding the following lines to your code:

```py
import os
os.environ["__NV_PRIME_RENDER_OFFLOAD"] = "1"
os.environ["__GLX_VENDOR_LIBRARY_NAME"] = "nvidia"
```

One of our friends asked a similar question on Discord and found this solution.

**Comment by ncheng89** [comment]
@compik710 Thank you very much for your answer. Now I have successfully called the gpu on the physical machine, but I cannot call the gpu inside docker. The gpu has been mapped inside the docker container. I can also use ffmpeg to test and can successfully call the gpu codec.

`root@rol-test-server:/opt/ms_rtmp/gltest# cat d.py 
import moderngl
import os
os.environ["__NV_PRIME_RENDER_OFFLOAD"] = "0"
os.environ["__GLX_VENDOR_LIBRARY_NAME"] = "nvidia"

#ctx = moderngl.create_standalone_context()
ctx = moderngl.create_context(standalone=True, backend='egl')
print("Vendor:", ctx.info['GL_VENDOR'])
print("Renderer:", ctx.info['GL_RENDERER'])
print("OpenGL version:", ctx.info['GL_VERSION'])
print("ModernGL version:", moderngl.__version__)
root@rol-test-server:/opt/ms_rtmp/gltest# python3 d.py 
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
OpenGL version: 3.3.0 NVIDIA 525.125.06
ModernGL version: 5.9.0
root@rol-test-server:/opt/ms_rtmp/gltest# docker exec -it av /bin/bash
root@554fda42bf96:/opt# cd ms_rtmp/gltest/
root@554fda42bf96:/opt/ms_rtmp/gltest# python3 d.py 
Vendor: Mesa/X.org
Renderer: llvmpipe (LLVM 11.0.1, 256 bits)
OpenGL version: 4.5 (Core Profile) Mesa 20.3.5
ModernGL version: 5.9.0
root@554fda42bf96:/opt/ms_rtmp/gltest# `

**Comment by compik710** [comment]
I found an article about Nvidia GPU in Docker. I'm not very familiar with Docker containers myself, but you can read about it: https://earthly.dev/blog/buildingrunning-nvidiacontainer/

You say that other applications have access to the GPU from the Docker container. The same article shows how you can limit the container to one GPU using command flags (try adding the `--gpus all` flag), you can try this.

**Comment by ncheng89** [comment]
Yes, the use of gpu in docker needs to be mapped through commands. When I start the docker container, I have mapped the gpu into it, and the status of the gpu can be displayed normally inside the container.
![image](https://github.com/moderngl/moderngl/assets/48044818/7b0c2ce7-cd0e-4529-9785-190546916069)

**Comment by szabolcsdombi** [comment]
Okay let's add more information to this issue.
The suggested response seems to be nVidia specific.

According to their [spec](https://docs.nvidia.com/gameworks/content/technologies/desktop/optimus.htm) the High Performance GPU can be requested on process load time by exporting:

```c++
extern "C" {
_declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
}
```

Also there is another value for AMD GPUs

```c++
extern "C" {
_declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 0x00000001;
}
```

Unfortunately this is not exported by the standard python executable. (It shouldn't be)
Once the process is started, the selected GPU is set in stone for OpenGL.

For this reason I have created [gpython](https://github.com/szabolcsdombi/gpython). Which at the moment is windows only prototype. the [gpython.c](https://github.com/szabolcsdombi/gpython/blob/main/gpython.c) is the main [python.c](https://github.com/python/cpython/blob/main/Programs/python.c) with the exports mentioned above.

```
pip install gpython
python -m gpython # this command installs gpython.exe alongside the original python.exe
gpython.exe ...
```

This tool is for development and soon will be supported on linux. I just have to find time to do it.

---

I have also created a more universal [python-game-launcher](https://github.com/szabolcsdombi/python-game-launcher)
which creates a standalone embedded python folder with a exe file in the project root.
This is a similar tool to [pyinstaller](https://pyinstaller.org/en/stable/), however I only plan to support linux with [wine](https://www.winehq.org/).
Basically the same thing as the gpython.exe, just fully isolated, with a hardcoded main module and a configurable icon.

---

Another solution is to run OpenGL over Vulkan. This can be done with [ANGLE](https://github.com/google/angle). The build must be configured to use the Vulkan backend, otherwise it will use DirectX 9 by default on Windows.
So far using this library works for my other rendering library.
With this method I can use the standard python executable and have the High Performance GPU do the rendering.
When I will find the time I will make it a proper Python Extension and add support for ModernGL.

This solution matches closely the subset what WebGL2 provides, and unfortunately some functions are not implemented (for example: glGetBufferSubData) which can be actually reimplemented with mapping the buffer for read.
Due to similar limitations, ModernGL with its heavy extension support might not benefit well from this. However an almost complete GLES 3.2 over Vulkan has most of the features ModernGL covers.

---

I hope this helps,
and I want to encourage anyone with extra information on this topic to add it below as comments.
📚 

PS: For me the most promising solution is ANGLE because it also allows [swiftshader](https://github.com/google/swiftshader) as a backend, which produces a 100% deterministic software rendered experience, which is better than a broken OpenGL implementation of a specific Hardware, which I unfortunately found plenty.
Angle also runs on DirectX and Metal so it would make our OpenGL apps somewhat more "native".

**Comment by szabolcsdombi** [comment]
There is another windows only trick which I intentionally left out of my previous comment.

This one-liner inserted as the first line of the python code also ensures the High Performance GPU.

```py
import ctypes; ctypes.WinDLL('vcamp110')
```

This should also work with the linux equivalent .so files using ctypes.CDLL.
The windows specific list that triggers the GPU switch is:
vcamp110.dll, vcamp110d.dll, nvapi.dll, nvapi64.dll, opencl.dll, nvcuda.dll, and cudart*.*

**Comment by ncheng89** [comment]
I have not encountered such a problem on the win system. moderngl will call my gpu resources by default, but on linux, I need to specify the gpu resources. What I don't understand now is why the docker container did not successfully call the gpu resources.

**Comment by compik710** [comment]
@ncheng89 show the output of the following command: `glxinfo | grep OpenGL`
You may not have access to the OpenGL library from Nvidia drivers in the Docker container.

**Comment by ncheng89** [comment]
![image](https://github.com/moderngl/moderngl/assets/48044818/6524b443-a93c-4d0b-8df0-37247d2e4376)
@compik710 look

**Comment by ncheng89** [comment]
![image](https://github.com/moderngl/moderngl/assets/48044818/96e6f68e-e79e-4119-ae87-a7577de5b31b)

The results from grep are consistent with the results on the physical machine. I feel that moderngl did not find the corresponding gpu resources.

**Comment by szabolcsdombi** [comment]
There are special steps to get certain hardware available inside the containers.
Once available, it is often necessary to use EGL to make a headless context.
EGL has some extensions for requesting the high performance GPU, however I never got that working.

Inside the containers the mesa drivers or similar might be out of date.
For this reason I can never use the base python docker images, instead I have to base my images on ubuntu. like [this](https://github.com/szabolcsdombi/zengl/blob/main/tests/Dockerfile).

**Comment by ncheng89** [comment]
Do I have to use the Ubuntu image? I built the container based on the Debian11 image. My physical machine system is an Ubuntu system. So, do you suggest using the Ubuntu image to build the container?
![image](https://github.com/moderngl/moderngl/assets/48044818/ccc4fbcb-3aba-4a6d-b45e-99c55222f67b)

**Comment by szabolcsdombi** [comment]
Your mesa 20 is from 2021 which is very old. Get Mesa up to date.

Here is a complete list:

```
FROM ubuntu:22.04
$ apt-get update && apt-get install -y mesa-vulkan-drivers vulkan-tools
$ vulkaninfo | grep Mesa
'DISPLAY' environment variable not set... skipping surface info
VK_LAYER_MESA_overlay (Mesa Overlay layer) Vulkan version 1.3.211, layer version 1:
        driverInfo         = Mesa 23.0.4-0ubuntu1~22.04.1 (LLVM 15.0.7)
        driverInfo                                           = Mesa 23.0.4-0ubuntu1~22.04.1 (LLVM 15.0.7)
```

```
FROM python:3.12.1
$ apt-get update && apt-get install -y mesa-vulkan-drivers vulkan-tools
$ vulkaninfo | grep Mesa
'DISPLAY' environment variable not set... skipping surface info
VK_LAYER_MESA_overlay (Mesa Overlay layer) Vulkan version 1.3.211, layer version 1:
        driverInfo      = Mesa 22.3.6 (LLVM 15.0.6)
        driverInfo                                           = Mesa 22.3.6 (LLVM 15.0.6)
```

```
FROM python:3.11.0
$ apt-get update && apt-get install -y mesa-vulkan-drivers vulkan-tools
$ vulkaninfo | grep Mesa
'DISPLAY' environment variable not set... skipping surface info
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
VK_LAYER_MESA_overlay (Mesa Overlay layer) Vulkan version 1.1.73, layer version 1:
        driverInfo         = Mesa 20.3.5 (LLVM 11.0.1)
```

```
FROM debian:11
$ apt-get update && apt-get install -y mesa-vulkan-drivers vulkan-tools
$ vulkaninfo | grep Mesa
'DISPLAY' environment variable not set... skipping surface info
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
VK_LAYER_MESA_overlay (Mesa Overlay layer) Vulkan version 1.1.73, layer version 1:
        driverInfo         = Mesa 20.3.5 (LLVM 11.0.1)
```

**Comment by szabolcsdombi** [comment]
You need a higher mesa version from inside the container, not on the host machine.

**Comment by ncheng89** [comment]
![image](https://github.com/moderngl/moderngl/assets/48044818/1a9a8635-529a-4620-8f09-105ee6121495)
The Debian11 system only provides the mesa20.3.5 release, and there is no higher version unless I change to the Ubuntu base image and rebuild it.

**Comment by ncheng89** [comment]
I seem to have found a way to use gpu in the container. When docker starts the container, it needs to be started with the --runtime=nvidia parameter instead of using --gpus device=1 alone. This is my complete command, docker run --runtime= nvidia --gpus device=1 --rm -it -v /opt/ms_rtmp:/opt/ms_rtmp -e DISPLAY -e XAUTHORITY -e NVIDIA_DRIVER_CAPABILITIES=all nicheng12/av_nvidia bash 
![image](https://github.com/moderngl/moderngl/assets/48044818/c1cded15-290e-4057-b2b0-3e7342f53d04)

**Comment by szabolcsdombi** [comment]
You have `LIBGL_ALWAYS_SOFTWARE=1`, probably it is not needed.

**Comment by compik710** [comment]
Cool, now the possibilities of ModernGL are open to you.

**Comment by ncheng89** [comment]
Yes, now you can successfully call the GPU without setting environment variables inside the container. Thank you very much for your support. 
![image](https://github.com/moderngl/moderngl/assets/48044818/92a46172-fe01-4f08-90af-7d58d60dd60e)
