### ISSUE TITLE
Does ModernGL actually use GPU memory on colab?

### ISSUE THREAD

**Issue by hlp-pls** [moderngl/moderngl#665]
You can check GPU usage on resources tab, but when using ModernGL, the GPU memory does not change. Also, the notebook keeps alerting me that I am not using GPU. 

The code I am using to create a context is like below. I then use this context to create and draw to framebuffers.
`CTX = moderngl.create_context(standalone=True, backend="egl", require=(330))`

**Comment by szabolcsdombi** [comment]
What is colab?
Can you please provide a code or link so I can check?
maybe you have libgl always software set in the env variables.

**Comment by hlp-pls** [comment]
I was referring to ["Google Colaboratory"](https://colab.research.google.com/?hl=ko).

You can check one my examples of using ModerGL with this [link](https://colab.research.google.com/drive/1mplNtAs0V-Wj9oqkzvc5BPpuD2HpzQQa?usp=sharing)

ModernGL does seem to work without connecting to a GPU runtime.

**Comment by szabolcsdombi** [comment]
I am not sure if this is related or useful but please take a quick look at:

https://github.com/google/navi/blob/main/gl/egl_context.py

I will ask on discord if anyone used moderngl on colab, I remember someone used it for sure.

**Comment by hlp-pls** [comment]
I found this comment on an issue on a different library that uses OpenGL. I think maybe this could be something.
https://github.com/mmatl/pyrender/issues/92#issuecomment-574571022

**Comment by compik710** [comment]
I can reproduce this problem. Google Colaboratory uses RAM memory instead of GPU (there is a separate tab where GPU memory is shown as unmeasured at all).

Code:
```py
import psutil as ps
import moderngl as mgl

ctx = mgl.create_context(standalone=True, backend='egl', require=(330))

last_measure = ps.virtual_memory().used
buf = ctx.buffer(reserve=32768**2)
current_measure = ps.virtual_memory().used

print('RAM filling:', (current_measure-last_measure)//1024//1024, 'MiB')
```
Output (may vary within 930-1040 MiB):
```
RAM filling: 958 MiB
```

![image](https://github.com/moderngl/moderngl/assets/68602173/c9d7e4f6-c539-4bc7-8794-0bb2be1e4138)

**Comment by compik710** [comment]
I can reproduce this problem. Google Colaboratory uses RAM memory instead of GPU (there is a separate tab where GPU memory is shown as unmeasured at all).

Code:
```py
import psutil as ps
import moderngl as mgl

ctx = mgl.create_context(standalone=True, backend='egl', require=(330))

last_measure = ps.virtual_memory().used
buf = ctx.buffer(reserve=32768**2)
current_measure = ps.virtual_memory().used

print('RAM filling:', (current_measure-last_measure)//1024//1024, 'MiB')
```
Output (may vary within 920-1040 MiB):
```
RAM filling: 928 MiB
```
![image](https://github.com/moderngl/moderngl/assets/68602173/1546774e-4d9a-445b-92fb-021996e912ac)

**Comment by compik710** [comment]
**Google Colaboratory** uses Docker containers to provide cloud computing services, so the problem is the same as here: #643

The `nvidia-smi` command works as expected, but the EGL context is created with the Mesa drivers.

```py
import moderngl as mgl

ctx = mgl.create_context(standalone=True, backend='egl')
print(ctx.info['GL_VENDOR'])
```
Output:
```
Mesa
```

True, I didn’t find the Docker container configuration settings, which means the situation here is more complicated.

**Comment by keepdying** [comment]
I have also similar issue, can't get it working on Dockerized environment (Kubernetes) with NVIDIA GPU present, I can use DL libraries with CUDA but no luck moderngl

**Comment by compik710** [comment]
I found a solution. @hlp-pls, @keepdying you can try this.

```
!apt install xvfb
```
```
!pip install -q xvfbwrapper moderngl[glcontext]
```
```py
from xvfbwrapper import Xvfb
import psutil as ps
import moderngl as mgl
import os

#os.environ["__NV_PRIME_RENDER_OFFLOAD"] = "1"
os.environ["__GLX_VENDOR_LIBRARY_NAME"] = "nvidia"
#os.environ['MESA_LOADER_DRIVER_OVERRIDE'] = "nvidia"

# For correct display opening
vdisplay = Xvfb()
vdisplay.start()
vdisplay.stop()

# Main code
vdisplay = Xvfb()
vdisplay.start()

ctx = mgl.create_context(standalone=True)

last_measure = ps.virtual_memory().used
buf = ctx.buffer(reserve=32768**2)
current_measure = ps.virtual_memory().used

print('RAM filling:', (current_measure-last_measure)//1024//1024, 'MiB')

print(ctx.info['GL_VENDOR'])
buf.release()
ctx.release()

vdisplay.stop()
```
Output:
```
RAM filling: 0 MiB
NVIDIA Corporation
```

At least it works for me.

**Comment by szabolcsdombi** [comment]
If anyone of you can link a project that uses OpenGL on colab probably in C or C++ it would allow us to make the same stepa in glcontext and add abackend="colab".
I expect actually egl to work so please don't ignore egl related projects.
Paste them here. The one that works can be used as reference to make the same egl calls on our side.

I have linked some google egl code. Which i expect they needed for similar reasons. (Maybe our egl backend was not doing what they needed)

**Comment by compik710** [comment]
@keepdying You can try different settings via `os.environ` like [here](https://askubuntu.com/a/1279633).
There are no other guesses yet.

**Comment by hlp-pls** [comment]
> I found a solution. @hlp-pls, @keepdying you can try this.
> 
> ```
> !apt install xvfb
> ```
> 
> ```
> !pip install -q xvfbwrapper moderngl[glcontext]
> ```
> 
> ```python
> from xvfbwrapper import Xvfb
> import psutil as ps
> import moderngl as mgl
> import os
> 
> #os.environ["__NV_PRIME_RENDER_OFFLOAD"] = "1"
> os.environ["__GLX_VENDOR_LIBRARY_NAME"] = "nvidia"
> #os.environ['MESA_LOADER_DRIVER_OVERRIDE'] = "nvidia"
> 
> # For correct display opening
> vdisplay = Xvfb()
> vdisplay.start()
> vdisplay.stop()
> 
> # Main code
> vdisplay = Xvfb()
> vdisplay.start()
> 
> ctx = mgl.create_context(standalone=True)
> 
> last_measure = ps.virtual_memory().used
> buf = ctx.buffer(reserve=32768**2)
> current_measure = ps.virtual_memory().used
> 
> print('RAM filling:', (current_measure-last_measure)//1024//1024, 'MiB')
> 
> print(ctx.info['GL_VENDOR'])
> buf.release()
> ctx.release()
> 
> vdisplay.stop()
> ```
> 
> Output:
> 
> ```
> RAM filling: 0 MiB
> NVIDIA Corporation
> ```
> 
> At least it works for me.

Okay this works for me! Thank you for your help. Now it runs much faster on GPU runtimes on Colaboratory. (much, much faster)

Does this code avoid setting egl with moderngl and uses some kind of virtual display with `xvfb` library?

**Comment by compik710** [comment]
Xvfb creates a virtual X framebuffer, which creates something like a virtual display (implementing an X11 server) and through it a headless context is created.

Since the video card is set by default via `
os.environ["__GLX_VENDOR_LIBRARY_NAME"] = "nvidia"`, Xvfb creates a display for Nvidia. This makes it possible to create a context for Nvidia via X11, which is what ModenrGL does by default.

I haven’t found a virtual server for EGL, so this is the only way for now. In essence, using Xvfb is a "hack". Alternatively, I think ModernGL could implement direct access to `libEGL.so` specifically by the location of the video card drivers, but for now it just looks for similar libraries throughout the system via `dlfcn.h`, which accidentally pulls up Mesa for CPU.

This theory is proven by the stable performance of ModernGL in colab before.

Instead of `libEGL.so` you need to specify `/path/to/video_card/drivers/libEGL.so`. To do this, you can automatically search for all similar libraries in the system and somehow automatically select the library of the most powerful GPU from the list. What do you think @szabolcsdombi?

**Comment by szabolcsdombi** [comment]
Can anyone check with a colab gpu instance the following?

```ipynb
[1] !apt install libvulkan-dev vulkan-tools
[2] !vulkaninfo
```

look for **VkPhysicalDeviceProperties** / **deviceType**

for me colab T4 gives a single GPU0 with `PHYSICAL_DEVICE_TYPE_CPU` type.

**Comment by compik710** [comment]
@szabolcsdombi I install this package:
```
!apt install libnvidia-gl-550
```

And now i see next picture:
```
deviceType        = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
deviceType        = PHYSICAL_DEVICE_TYPE_CPU
```

By the way, ModernGL also worked:
```py
from glcontext import egl
import moderngl as mgl

egl.create_context(mode='standalone')

mgl.init_context()
ctx = mgl.get_context()
print(ctx.info['GL_VENDOR'])
```
```
NVIDIA Corporation
```

**Comment by szabolcsdombi** [comment]
I think the above message by @compik710 guarantees a discrete GPU device to be used.

It is often better not to pull into the process memory the entire X11 stack. For that EGL is best.

Please reopen the issue if it is still not working.

**Comment by compik710** [comment]
Just in case, I checked: installing `libnvidia-gl-525` or `libnvidia-gl-535` solves the problem exactly the same. So the problem here was probably the lack of drivers.
