### ISSUE TITLE
Can't get it working in Kubernetes environment with NVIDIA GPU

### ISSUE THREAD

**Issue by keepdying** [moderngl/moderngl#666]
I developed a service to serve some rendered graphics with moderngl. However I can't get it working on my Kubernetes cluster.

using official nvidia gpu operator (not gke) with moderngl 5.10

Current situation:
I am trying this official nvidia cudagl image:
```
nvidia/cudagl:11.3.0-devel-ubuntu20.04
```
with these packages:
```
libnvidia-gl-525
libglvnd-dev
```
also pointed to nvidia directly.
```bash
export __EGL_VENDOR_LIBRARY_FILENAMES="/usr/share/glvnd/egl_vendor.d/10_nvidia.json"
```
I can see GPU with nvidia-smi,
also I can use PyTorch or other DL libraries.

creating context like
```
ctx.create_context(standalone=True, backend="egl")
```
getting this egl error
```
requested device index 0, but found 0 devices
```

**Comment by compik710** [comment]
What version of Ubuntu do you have? If the version is too old, ModernGL may have problems creating an EGL context.

**Comment by szabolcsdombi** [comment]
@compik710 

Once i made a new egl contecxt backend for glcontext. However it does not build on the CI with cibuildwheeld because of the old apt or mesa at hand.

Look in the glcontext repo: glcontext/headless.cpp

I plan to make this a separate repo/module

I am not sure if you can try to build it and run it. I am not i a shape to do it anytime soon.

There is a method to list devices. And there is another method to create a context. Pass it as a loader to init_context.

Some disambiguation.

This code above creates an egl context.
What we recently added in 5.10 just**detects** egl contexts properly.

So the code in headless.cpp could be very useful here.

There may be a test.py in the glcontext root which just prints some functions form GL using only the glcontext. This allows testing the context creation manually without moderngl.

It should be easy to hack on the headless.cpp there are egl flavs to ask for high perf gpu and similar.

**Comment by keepdying** [comment]
I tried to hack with this small c program:
`c
#include <EGL/egl.h>
#include <EGL/eglext.h>

#include <stdio.h>
#include <stdlib.h>

typedef EGLBoolean (*eglQueryDevicesEXTProc)(EGLint, EGLDeviceEXT *, EGLint *);

int main()
{
  eglQueryDevicesEXTProc eglQueryDevicesEXT = (eglQueryDevicesEXTProc)eglGetProcAddress("eglQueryDevicesEXT");
  if (!eglQueryDevicesEXT)
  {
    printf("Failed to get proc address for eglQueryDevicesEXT\n");
    return -1;
  }

  EGLint num_devices;

  if (eglQueryDevicesEXT(0, NULL, &num_devices) == EGL_FALSE)
  {
    printf("eglQueryDevicesEXT failed\n");
    return -1;
  }

  printf("Device count: %d\n", num_devices);

  return 0;
}
`
Got 0 device count also, so i think it is a EGL thing rather than glcontext?

**Comment by szabolcsdombi** [comment]
https://github.com/szabolcsdombi/zengl/commit/e65191b86f5f39acd9966217c8bc75abc97afe6d

Please see the removed code uses headless.cpp

**Comment by szabolcsdombi** [comment]
Your c program now can be ysed to search for a more generic issue: How to get EGL working in colab

**Comment by szabolcsdombi** [comment]
https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/differentiable-parameterizations/appendix/colab_gl.ipynb

Maybe useful. If lucid create context works we should be able to detect it

**Comment by keepdying** [comment]
@compik710 found a workaround for running in colab with xvfb and x11 but in my containerized kubernetes environment it didn't work. Mounting /tmp/.x11-unix also didnt work. Maybe it is due to how NVIDIA GPU Operator passes GPUs to containers? I'll check for the links you posted tomorrow and update my findings.

**Comment by compik710** [comment]
I tried to set the driver libraries manually, but for some reason it didn’t work (`ctx.info` return **Mesa** as vendor).
[`glcontext/egl.cpp`](https://github.com/moderngl/glcontext/blob/1573e57e5423b313599155c7e4bc9c5253065f40/glcontext/egl.cpp#L97C1-L98C39):
```c
...
    const char * libgl = "/usr/lib64-nvidia/libGL.so.1";
    const char * libegl = "/usr/lib64-nvidia/libEGL.so.1";
...
```
<details>
<summary>Test</summary>

* Code
```py
import moderngl as mgl
from glcontext import egl


egl.create_context(mode="standalone")

ctx = mgl.get_context()
print(ctx.info['GL_VENDOR'])
```

* Output
```
Mesa
```

</details>

<br>

Also tried [`glcontext/headless.cpp`](https://github.com/moderngl/glcontext/blob/master/glcontext/headless.cpp), but it breaks the build of **glcontext** and makes it untestable.

> https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/differentiable-parameterizations/appendix/colab_gl.ipynb
>
> Maybe useful. If lucid create context works we should be able to detect it

[lucid](https://github.com/tensorflow/lucid) is no longer buildable, and attempting to build it yourself results in errors. Its older versions do not support the Tensorflow (dependency) functionality that has changed since then, so we can say that this repository is archived and cannot help us.

**Comment by compik710** [comment]
EDIT: `glcontext` is not built in colab at all.

Code:
```py
!rm -rf glcontext
!git clone https://github.com/moderngl/glcontext

%cd glcontext
!python -m pip install -e .
%cd ..
!rm -rf glcontext
```
```py
from glcontext import egl
```
Output:
```py
ModuleNotFoundError: No module named 'glcontext'
```

This means that the check for `/usr/lib64-nvidia/libEGL.so` has not yet passed.

**Comment by compik710** [comment]
@szabolcsdombi Using the PYPI version of moderngl and glcontext, I found a way to manually specify the libraries, but a strange error occurs.

Code
```py
from glcontext import egl
import moderngl as mgl

egl.create_context(libgl='/usr/lib64-nvidia/libGL.so.1.7.0', libegl='/usr/lib64-nvidia/libEGL_nvidia.so.535.104.05', mode="standalone")

ctx = mgl.get_context()
print(ctx.info['GL_VENDOR'])
```
Output
```
----> egl.create_context(libgl='/usr/lib64-nvidia/libGL.so.1.7.0', libegl='/usr/lib64-nvidia/libEGL_nvidia.so.535.104.05', mode="standalone")
Exception: eglGetError not found
```

It's like the libraries are empty.

**Comment by compik710** [comment]
@keepdying I think that EGL cannot find devices precisely because the driver versions differ from the package versions.

> Current situation:
> I am trying this official nvidia cudagl image:
>```
> nvidia/cudagl:11.3.0-devel-ubuntu20.04
> ```
> with these packages:
> ```
> libnvidia-gl-525
> libglvnd-dev
> ```

Ubuntu 20.04 came out in 2020, libnvidia-gl-525 drivers came out around 2022-2023, and libglvnd-dev is practically up-to-date. Such differences in versions can ruin the connection between the device and programs that simply stop seeing it:
> getting this egl error
> ```
> requested device index 0, but found 0 devices
> ```

I'm afraid without updating the error may remain. Other libraries, such as PyTorch, continue to work because they use CUDA, with which it is much easier to maintain backward compatibility, since it is almost independent of the system, much less the servers X.org, Wayland and the like.

Are you really that limited by outdated software versions?

**Comment by keepdying** [comment]
> @keepdying I think that EGL cannot find devices precisely because the driver versions differ from the package versions.
> 
> > Current situation:
> > I am trying this official nvidia cudagl image:
> > ```
> > nvidia/cudagl:11.3.0-devel-ubuntu20.04
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with these packages:
> > ```
> > libnvidia-gl-525
> > libglvnd-dev
> > ```
> 
> Ubuntu 20.04 came out in 2020, libnvidia-gl-525 drivers came out around 2022-2023, and libglvnd-dev is practically up-to-date. Such differences in versions can ruin the connection between the device and programs that simply stop seeing it:
> 
> > getting this egl error
> > ```
> > requested device index 0, but found 0 devices
> > ```
> 
> I'm afraid without updating the error may remain. Other libraries, such as PyTorch, continue to work because they use CUDA, with which it is much easier to maintain backward compatibility, since it is almost independent of the system, much less the servers X.org, Wayland and the like.
> 
> Are you really that limited by outdated software versions?

No, Ubuntu version is not the issue here.

I tried this similar image:
nvidia/opengl:1.2-glvnd-devel-ubuntu22.04

got the same error.

However I found this custom made base image for egl

```
https://github.com/selkies-project/docker-nvidia-egl-desktop
ghcr.io/selkies-project/nvidia-egl-desktop:latest
```

now I can see 2 devices in egl but I get this error:

```
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
```

**Comment by compik710** [comment]
@keepdying great, now EGL sees the devices.

Your next step:
Option 1: [Update](https://us.download.nvidia.com/XFree86/Linux-x86_64/550.40.07/README/installdriver.html) Nvidia drivers to the latest version [(not stable, but latest)](https://www.nvidia.com/Download/driverResults.aspx/218119/en-us/) [[recomendation from similar issue]](https://forums.developer.nvidia.com/t/hardware-egl-not-working-on-wayland-libegl-warning-egl-failed-to-create-dri2-screen/262167)
Option 2: Install `libnvidia-egl-wayland1` [[recomendation from similar issue]](https://github.com/telegramdesktop/tdesktop/issues/26787)
Option 3: Do both of the above points.

**Comment by compik710** [comment]
@keepdying simplified alternative for the first option: `apt install libnvidia-gl-550`

**Comment by keepdying** [comment]
@compik710 I don't manage the Kubernetes cluster directly, but I will try to get a test environment with latest drivers.

**Comment by keepdying** [comment]
latest version for Data Center GPUs are 535 so I am stuck with it.

**Comment by szabolcsdombi** [comment]
some gpus are dedicated for compute, they can run ai models pretty well, but they miss the cores dedicated for texture sampling, vertex assembly and similar, so they are not useful for graphics.
make sure you are using graphics compatible gpus.

(graphics compatible graphics processing units, nice!)

**Comment by keepdying** [comment]
I managed to get it running with
`ghcr.io/selkies-project/nvidia-egl-desktop:latest
`
with deployment with provided yaml in its repo.
